name = "IterativeReweightedLeastSquares"
uuid = "2ae1257b-8b4a-4b74-9b35-54e3b3b01207"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
